import mongoose from "mongoose";
import { manufacturerDb } from "../../lib/db.js";
import Inventory from "../../models/Inventory.js";
import Branch from "../../models/Branch.js";
import Barcode from "../../models/Barcode.js";
import Design from "../../models/Design.js";
import GemstoneParcel from "../../models/GemstoneParcel.js";
import Vendor from "../../models/Vendor.js";
import Rate from "../../models/Rate.js";
import Karikar from "../../models/Karikar.js";
import Order from "../../models/Order.js";
import RetailerOrderModel from "../../models/RetailerOrder.js";
import Sale from "../../models/Sale.js";
import Khata from "../../models/Khata.js";
import { SchemeDefinition, SchemeEnrollment } from "../../models/Scheme.js";
import OldGoldExchange from "../../models/OldGoldExchange.js";
import Offer from "../../models/Offer.js";
import User from "../../models/User.js";
import Task from "../../models/Task.js";
import ConsignmentStock from "../../models/ConsignmentStock.js";
import MetalMelting from "../../models/MetalMelting.js";
import WholesaleOrder from "../../models/WholesaleOrder.js";
import SalesReturn from "../../models/SalesReturn.js";
import HallmarkBatch from "../../models/HallmarkBatch.js";
import ComplianceRecord from "../../models/ComplianceRecord.js";
import AccountingEntry from "../../models/AccountingEntry.js";
import SubscriptionSchema from "../../superadmin/models/Subscription.js";
import Installment from "../../models/Installment.js";
import PurchaseOrder from "../../models/PurchaseOrder.js";
import DesignMoodboard from "../../models/DesignMoodboard.js";
import DesignMoodboardAuditLog from "../../models/DesignMoodboardAuditLog.js";
import DesignApproval from "../../models/DesignApproval.js";
import DesignApprovalAuditLog from "../../models/DesignApprovalAuditLog.js";

export const ManufacturerBranch = manufacturerDb.models.Branch || manufacturerDb.model("Branch", Branch.schema, "branches");
export const ManufacturerInventory = manufacturerDb.models.Inventory || manufacturerDb.model("Inventory", Inventory.schema, "inventory");
export const ManufacturerBarcode = manufacturerDb.models.Barcode || manufacturerDb.model("Barcode", Barcode.schema, "barcodes");
export const ManufacturerDesign = manufacturerDb.models.Design || manufacturerDb.model("Design", Design.schema, "catalog");
export const ManufacturerGemstoneParcel = manufacturerDb.models.GemstoneParcel || manufacturerDb.model("GemstoneParcel", GemstoneParcel.schema, "gemstones");
export const ManufacturerVendor = manufacturerDb.models.Vendor || manufacturerDb.model("Vendor", Vendor.schema, "vendors");
export const ManufacturerRate = manufacturerDb.models.Rate || manufacturerDb.model("Rate", Rate.schema, "rates");
export const ManufacturerKarikar = manufacturerDb.models.Karikar || manufacturerDb.model("Karikar", Karikar.schema, "karikars");
export const ManufacturerOrder = manufacturerDb.models.Order || manufacturerDb.model("Order", Order.schema, "orders");
export const ManufacturerRetailerOrder = manufacturerDb.models.RetailerOrder || manufacturerDb.model("RetailerOrder", RetailerOrderModel.schema, "retailerorders");
export const ManufacturerSale = manufacturerDb.models.Sale || manufacturerDb.model("Sale", Sale.schema, "sales");
export const ManufacturerKhata = manufacturerDb.models.Khata || manufacturerDb.model("Khata", Khata.schema, "khata");
export const ManufacturerSchemeDefinition = manufacturerDb.models.SchemeDefinition || manufacturerDb.model("SchemeDefinition", SchemeDefinition.schema, "schemes");
export const ManufacturerSchemeEnrollment = manufacturerDb.models.SchemeEnrollment || manufacturerDb.model("SchemeEnrollment", SchemeEnrollment.schema, "schemeenrollments");
export const ManufacturerOldGoldExchange = manufacturerDb.models.OldGoldExchange || manufacturerDb.model("OldGoldExchange", OldGoldExchange.schema, "oldgold");
export const ManufacturerOffer = manufacturerDb.models.Offer || manufacturerDb.model("Offer", Offer.schema, "offers");
export const ManufacturerUser = manufacturerDb.models.User || manufacturerDb.model("User", User.schema, "users");
export const ManufacturerTask = manufacturerDb.models.Task || manufacturerDb.model("Task", Task.schema, "tasks");
export const ManufacturerConsignmentStock = manufacturerDb.models.ConsignmentStock || manufacturerDb.model("ConsignmentStock", ConsignmentStock.schema, "consignmentstocks");
export const ManufacturerMetalMelting = manufacturerDb.models.MetalMelting || manufacturerDb.model("MetalMelting", MetalMelting.schema, "metalmeltings");
export const ManufacturerWholesaleOrder = manufacturerDb.models.WholesaleOrder || manufacturerDb.model("WholesaleOrder", WholesaleOrder.schema, "wholesale");
export const ManufacturerSalesReturn = manufacturerDb.models.SalesReturn || manufacturerDb.model("SalesReturn", SalesReturn.schema, "returns");
export const ManufacturerHallmarkBatch = manufacturerDb.models.HallmarkBatch || manufacturerDb.model("HallmarkBatch", HallmarkBatch.schema, "hallmarking");
export const ManufacturerComplianceRecord = manufacturerDb.models.ComplianceRecord || manufacturerDb.model("ComplianceRecord", ComplianceRecord.schema, "compliance");
export const ManufacturerAccountingEntry = manufacturerDb.models.AccountingEntry || manufacturerDb.model("AccountingEntry", AccountingEntry.schema, "accounting");
export const ManufacturerSubscription = (manufacturerDb.models.Subscription || manufacturerDb.model("Subscription", SubscriptionSchema, "subscriptions")) as mongoose.Model<any>;
export const ManufacturerInstallment = manufacturerDb.models.Installment || manufacturerDb.model("Installment", Installment.schema, "installments");
export const ManufacturerPurchaseOrder = (manufacturerDb.models.PurchaseOrder || manufacturerDb.model("PurchaseOrder", PurchaseOrder.schema, "purchaseorders")) as mongoose.Model<any>;
export const ManufacturerDesignMoodboard = manufacturerDb.models.DesignMoodboard || manufacturerDb.model("DesignMoodboard", DesignMoodboard.schema, "designmoodboards");
export const ManufacturerDesignMoodboardAuditLog = manufacturerDb.models.DesignMoodboardAuditLog || manufacturerDb.model("DesignMoodboardAuditLog", DesignMoodboardAuditLog.schema, "designmoodboardauditlogs");
export const ManufacturerDesignApproval = manufacturerDb.models.DesignApproval || manufacturerDb.model("DesignApproval", DesignApproval.schema, "designapprovals");
export const ManufacturerDesignApprovalAuditLog = manufacturerDb.models.DesignApprovalAuditLog || manufacturerDb.model("DesignApprovalAuditLog", DesignApprovalAuditLog.schema, "designapprovalauditlogs");
