import mongoose from "mongoose";
import { retailerDb } from "../../lib/db.js";
import InventorySchema from "../../models/Inventory.js";
import BranchSchema from "../../models/Branch.js";
import CustomerSchema from "../../models/Customer.js";
import VendorSchema from "../../models/Vendor.js";
import SaleSchema from "../../models/Sale.js";
import OrderSchema from "../../models/Order.js";
import KhataSchema from "../../models/Khata.js";
import RateSchema from "../../models/Rate.js";
import RepairJobSchema from "../../models/RepairJob.js";
import RFIDTagSchema from "../../models/RFIDTag.js";
import PortalCheckoutSchema from "../../models/PortalCheckout.js";
import RetailerOrderSchema from "../../models/RetailerOrder.js";
import UserSchema from "../../models/User.js";
import { SchemeDefinition as SchemeDefinitionSchema, SchemeEnrollment as SchemeEnrollmentSchema } from "../../models/Scheme.js";
import ChequeEmiSchema from "../../models/ChequeEmi.js";
import CashDenominationSchema from "../../models/CashDenomination.js";
import BarcodeModel from "../../models/Barcode.js";
import AdvanceInventoryModel from "../../models/AdvanceInventory.js";
import UserRoleModel from "../../models/UserRole.js";
import SubscriptionSchema from "../../superadmin/models/Subscription.js";
import ConsignmentStockSchema from "../../models/ConsignmentStock.js";
import TaskSchema from "../../models/Task.js";
import Form60Schema from "../../models/Form60.js";
import KarikarSchema from "../../models/Karikar.js";
import NotificationSchema from "../../models/Notification.js";
import WastageReconciliationSchema from "../../models/WastageReconciliation.js";
import KarikarWageLedgerSchema from "../../models/KarikarWageLedger.js";
import ShiftScheduleSchema from "../../models/ShiftSchedule.js";
import InvoiceSchema from "../../models/Invoice.js";
import InvoiceSeriesSchema from "../../models/InvoiceSeries.js";
import InvoiceProfileSchema from "../../models/InvoiceProfile.js";
import PaymentLedgerSchema from "../../models/PaymentLedger.js";
import AdvanceDepositSchema from "../../models/AdvanceDeposit.js";
import EmiPlanSchema from "../../models/EmiPlan.js";
import FinanceAuditLogSchema from "../../models/FinanceAuditLog.js";
import SalesReturnSchema from "../../models/SalesReturn.js";
import BisCertificateSchema from "../../models/BisCertificate.js";
import ComplianceLogSchema from "../../models/ComplianceLog.js";
import ImportHistoryModel from "../../models/ImportHistory.js";
import BarcodePrintHistoryModel from "../../models/BarcodePrintHistory.js";
import CatalogueAuditLogModel from "../../models/CatalogueAuditLog.js";
import JobCardSchema from "../../models/JobCard.js";
import DesignMoodboardModel from "../../models/DesignMoodboard.js";
import DesignMoodboardAuditLogModel from "../../models/DesignMoodboardAuditLog.js";
import DesignApprovalModel from "../../models/DesignApproval.js";
import DesignApprovalAuditLogModel from "../../models/DesignApprovalAuditLog.js";
import CostEstimateAuditLogModel from "../../models/CostEstimateAuditLog.js";
import DesignRevisionModel from "../../models/DesignRevision.js";
import CostEstimateModel from "../../models/CostEstimate.js";
import OrderTrackingSchema from "../../models/OrderTracking.js";
import CustomerReferralSchema from "../../models/CustomerReferral.js";
import MakingChargeRuleSchema from "../../models/MakingChargeRule.js";
import FinancialYearSchema from "../../models/FinancialYear.js";
import TaxProfileSchema from "../../models/TaxProfile.js";
import MessagingConfigurationSchema from "../../models/MessagingConfiguration.js";
import PaymentGatewayConfigurationSchema from "../../models/PaymentGatewayConfiguration.js";
import PrinterConfigurationSchema from "../../models/PrinterConfiguration.js";
import TCSTransactionSchema from "../../models/TCSTransaction.js";
import BISLicenceSchema from "../../models/BISLicence.js";
import TenantBrandingSchema from "../../models/TenantBranding.js";
import TenantThemeSchema from "../../models/TenantTheme.js";
import TenantDomainSchema from "../../models/TenantDomain.js";
import TenantEmailTemplateSchema from "../../models/TenantEmailTemplate.js";
import TenantAppSettingsSchema from "../../models/TenantAppSettings.js";
import ReferralPartnerSchema from "../../models/ReferralPartner.js";
import ReferralLeadSchema from "../../models/ReferralLead.js";
import ReferralCommissionSchema from "../../models/ReferralCommission.js";
import ReferralPayoutLedgerSchema from "../../models/ReferralPayoutLedger.js";
import VendorRateContractSchema from "../../models/VendorRateContract.js";
import VendorRateRuleSchema from "../../models/VendorRateRule.js";
import PriceResolutionLogModelDefault, { PriceResolutionLogSchema } from "../../models/PriceResolutionLog.js";

export const Inventory = retailerDb.models.Inventory || retailerDb.model("Inventory", InventorySchema.schema, "inventory");
export const Branch = retailerDb.models.Branch || retailerDb.model("Branch", BranchSchema.schema, "branches");
export const Customer = retailerDb.models.Customer || retailerDb.model("Customer", CustomerSchema.schema, "customers");
export const Vendor = retailerDb.models.Vendor || retailerDb.model("Vendor", VendorSchema.schema, "vendors");
export const Sale = retailerDb.models.Sale || retailerDb.model("Sale", SaleSchema.schema, "sales");
export const Order = retailerDb.models.Order || retailerDb.model("Order", OrderSchema.schema, "orders");
export const Khata = retailerDb.models.Khata || retailerDb.model("Khata", KhataSchema.schema, "khata");
export const Rate = retailerDb.models.Rate || retailerDb.model("Rate", RateSchema.schema, "rates");
export const RepairJob = retailerDb.models.RepairJob || retailerDb.model("RepairJob", RepairJobSchema.schema, "repairjobs");
export const RFIDTag = retailerDb.models.RFIDTag || retailerDb.model("RFIDTag", RFIDTagSchema.schema, "rfidtags");
export const PortalCheckout = retailerDb.models.PortalCheckout || retailerDb.model("PortalCheckout", PortalCheckoutSchema.schema, "portalcheckouts");
export const RetailerOrder = retailerDb.models.RetailerOrder || retailerDb.model("RetailerOrder", RetailerOrderSchema.schema, "retailerorders");
export const User = retailerDb.models.User || retailerDb.model("User", UserSchema.schema, "users");
export const Notification = (retailerDb.models.Notification || retailerDb.model("Notification", NotificationSchema, "notifications")) as mongoose.Model<any>;
export const SchemeDefinition = retailerDb.models.SchemeDefinition || retailerDb.model("SchemeDefinition", SchemeDefinitionSchema.schema, "schemes");
export const SchemeEnrollment = retailerDb.models.SchemeEnrollment || retailerDb.model("SchemeEnrollment", SchemeEnrollmentSchema.schema, "schemeenrollments");
export const ChequeEmi = retailerDb.models.ChequeEmi || retailerDb.model("ChequeEmi", ChequeEmiSchema.schema, "chequeemis");
export const CashDenomination = retailerDb.models.CashDenomination || retailerDb.model("CashDenomination", CashDenominationSchema.schema, "cashdenominations");
export const Barcode = retailerDb.models.Barcode || retailerDb.model("Barcode", BarcodeModel.schema, "barcodes");
export const AdvanceInventory = retailerDb.models.AdvanceInventory || retailerDb.model("AdvanceInventory", AdvanceInventoryModel.schema, "advanceinventories");
export const UserRole = retailerDb.models.UserRole || retailerDb.model("UserRole", UserRoleModel.schema, "userroles");
export const Subscription = (retailerDb.models.Subscription || retailerDb.model("Subscription", SubscriptionSchema, "subscriptions")) as mongoose.Model<any>;
export const ConsignmentStock = retailerDb.models.ConsignmentStock || retailerDb.model("ConsignmentStock", ConsignmentStockSchema.schema, "consignmentstocks");
export const Task = retailerDb.models.Task || retailerDb.model("Task", TaskSchema.schema, "tasks");
export const Form60 = retailerDb.models.Form60 || retailerDb.model("Form60", Form60Schema.schema, "form60");
export const Karikar = retailerDb.models.Karikar || retailerDb.model("Karikar", KarikarSchema.schema, "karikars");
export const WastageReconciliation = retailerDb.models.WastageReconciliation || retailerDb.model("WastageReconciliation", WastageReconciliationSchema.schema, "wastagereconciliations");
export const KarikarWageLedger =
  retailerDb.models.KarikarWageLedger ||
  retailerDb.model("KarikarWageLedger", KarikarWageLedgerSchema.schema, "karikarwageledgers");
export const ShiftSchedule = retailerDb.models.ShiftSchedule || retailerDb.model("ShiftSchedule", ShiftScheduleSchema.schema, "shiftschedules");
export const Invoice = retailerDb.models.Invoice || retailerDb.model("Invoice", InvoiceSchema.schema, "invoices");
export const InvoiceSeries = retailerDb.models.InvoiceSeries || retailerDb.model("InvoiceSeries", InvoiceSeriesSchema.schema, "invoiceseries");
export const InvoiceProfile = retailerDb.models.InvoiceProfile || retailerDb.model("InvoiceProfile", InvoiceProfileSchema.schema, "invoiceprofiles");
export const PaymentLedger = retailerDb.models.PaymentLedger || retailerDb.model("PaymentLedger", PaymentLedgerSchema.schema, "paymentledgers");
export const AdvanceDeposit = retailerDb.models.AdvanceDeposit || retailerDb.model("AdvanceDeposit", AdvanceDepositSchema.schema, "advancedeposits");
export const EmiPlan = retailerDb.models.EmiPlan || retailerDb.model("EmiPlan", EmiPlanSchema.schema, "emiplans");
export const FinanceAuditLog = retailerDb.models.FinanceAuditLog || retailerDb.model("FinanceAuditLog", FinanceAuditLogSchema.schema, "financeauditlogs");
export const SalesReturn = retailerDb.models.SalesReturn || retailerDb.model("SalesReturn", SalesReturnSchema.schema, "salesreturns");
export const BisCertificate = retailerDb.models.BisCertificate || retailerDb.model("BisCertificate", BisCertificateSchema.schema, "biscertificates");
export const ComplianceLog = retailerDb.models.ComplianceLog || retailerDb.model("ComplianceLog", ComplianceLogSchema.schema, "compliancelogs");
export const ImportHistory = retailerDb.models.ImportHistory || retailerDb.model("ImportHistory", ImportHistoryModel.schema, "importhistories");
export const BarcodePrintHistory = retailerDb.models.BarcodePrintHistory || retailerDb.model("BarcodePrintHistory", BarcodePrintHistoryModel.schema, "barcodeprinthistories");
export const CatalogueAuditLog = retailerDb.models.CatalogueAuditLog || retailerDb.model("CatalogueAuditLog", CatalogueAuditLogModel.schema, "catalogueauditlogs");
export const JobCard = retailerDb.models.JobCard || retailerDb.model("JobCard", JobCardSchema.schema, "jobcards");
export const DesignMoodboard = retailerDb.models.DesignMoodboard || retailerDb.model("DesignMoodboard", DesignMoodboardModel.schema, "designmoodboards");
export const DesignMoodboardAuditLog = retailerDb.models.DesignMoodboardAuditLog || retailerDb.model("DesignMoodboardAuditLog", DesignMoodboardAuditLogModel.schema, "designmoodboardauditlogs");
export const DesignApproval = retailerDb.models.DesignApproval || retailerDb.model("DesignApproval", DesignApprovalModel.schema, "designapprovals");
export const DesignApprovalAuditLog = retailerDb.models.DesignApprovalAuditLog || retailerDb.model("DesignApprovalAuditLog", DesignApprovalAuditLogModel.schema, "designapprovalauditlogs");
export const CostEstimateAuditLog = retailerDb.models.CostEstimateAuditLog || retailerDb.model("CostEstimateAuditLog", CostEstimateAuditLogModel.schema, "costestimateauditlogs");
export const DesignRevision = retailerDb.models.DesignRevision || retailerDb.model("DesignRevision", DesignRevisionModel.schema, "designrevisions");
export const CostEstimate = retailerDb.models.CostEstimate || retailerDb.model("CostEstimate", CostEstimateModel.schema, "costestimates");
export const OrderTracking = retailerDb.models.OrderTracking || retailerDb.model("OrderTracking", OrderTrackingSchema.schema, "ordertrackings");
export const CustomerReferral = retailerDb.models.CustomerReferral || retailerDb.model("CustomerReferral", CustomerReferralSchema.schema, "customerreferrals");
export const MakingChargeRule = retailerDb.models.MakingChargeRule || retailerDb.model("MakingChargeRule", MakingChargeRuleSchema.schema, "makingchargerules");
export const FinancialYear = retailerDb.models.FinancialYear || retailerDb.model("FinancialYear", FinancialYearSchema.schema, "financialyears");
export const TaxProfile = retailerDb.models.TaxProfile || retailerDb.model("TaxProfile", TaxProfileSchema.schema, "taxprofiles");
export const MessagingConfiguration = retailerDb.models.MessagingConfiguration || retailerDb.model("MessagingConfiguration", MessagingConfigurationSchema.schema, "messagingconfigurations");
export const PaymentGatewayConfiguration = retailerDb.models.PaymentGatewayConfiguration || retailerDb.model("PaymentGatewayConfiguration", PaymentGatewayConfigurationSchema.schema, "paymentgatewayconfigurations");
export const PrinterConfiguration = retailerDb.models.PrinterConfiguration || retailerDb.model("PrinterConfiguration", PrinterConfigurationSchema.schema, "printerconfigurations");
export const TCSTransaction = retailerDb.models.TCSTransaction || retailerDb.model("TCSTransaction", TCSTransactionSchema.schema, "tcstransactions");
export const BISLicence = retailerDb.models.BISLicence || retailerDb.model("BISLicence", BISLicenceSchema.schema, "bislicences");
export const TenantBranding = retailerDb.models.TenantBranding || retailerDb.model("TenantBranding", TenantBrandingSchema.schema, "tenantbrandings");
export const TenantTheme = retailerDb.models.TenantTheme || retailerDb.model("TenantTheme", TenantThemeSchema.schema, "tenantthemes");
export const TenantDomain = retailerDb.models.TenantDomain || retailerDb.model("TenantDomain", TenantDomainSchema.schema, "tenantdomains");
export const TenantEmailTemplate = retailerDb.models.TenantEmailTemplate || retailerDb.model("TenantEmailTemplate", TenantEmailTemplateSchema.schema, "tenantemailtemplates");
export const TenantAppSettings = retailerDb.models.TenantAppSettings || retailerDb.model("TenantAppSettings", TenantAppSettingsSchema.schema, "tenantappsettings");
export const ReferralPartner = retailerDb.models.ReferralPartner || retailerDb.model("ReferralPartner", ReferralPartnerSchema.schema, "referralpartners");
export const ReferralLead = retailerDb.models.ReferralLead || retailerDb.model("ReferralLead", ReferralLeadSchema.schema, "referralleads");
export const ReferralCommission = retailerDb.models.ReferralCommission || retailerDb.model("ReferralCommission", ReferralCommissionSchema.schema, "referralcommissions");
export const ReferralPayoutLedger = retailerDb.models.ReferralPayoutLedger || retailerDb.model("ReferralPayoutLedger", ReferralPayoutLedgerSchema.schema, "referralpayoutledgers");
export const VendorRateContract = retailerDb.models.VendorRateContract || retailerDb.model("VendorRateContract", VendorRateContractSchema.schema, "vendorratecontracts");
export const VendorRateRule = retailerDb.models.VendorRateRule || retailerDb.model("VendorRateRule", VendorRateRuleSchema.schema, "vendorraterules");
export const PriceResolutionLog = (retailerDb.models.PriceResolutionLog || retailerDb.model("PriceResolutionLog", PriceResolutionLogSchema, "priceresolutionlogs")) as mongoose.Model<any>;



