import mongoose from "mongoose";

const karikarSchema = new mongoose.Schema({
  name: { type: String, required: true },
  email: String,
  password: String,
  aadhar: String,
  phone: String,
  emergencyContact: String,
  address: String,
  profilePhoto: String,
  skills: [String],
  specialization: String,
  jewelleryTypes: [String],
  goldExperience: Number,
  silverExperience: Number,
  diamondExperience: Number,
  platinumExperience: Number,
  dailyCapacity: Number,
  hourlyRate: Number,
  wageType: String,
  goldStock: { type: Number, default: 0 },
  ledgerBalance: { type: Number, default: 0 },
  jobCards: [{
    _id: { type: String },
    orderId: { type: String },
    issuedGrossWeight: { type: Number, default: 0 },
    issuedAlloy: { type: Number, default: 0 },
    issuedGoldWeight: { type: Number, default: 0 },
    issuedPurity: { type: String },
    issuedStones: [{ stoneId: String, carat: Number }],
    dueDate: { type: String },
    status: { type: String, default: "OPEN" },
    issuedAt: { type: String },
    receivedGrossWeight: { type: Number },
    receivedNetWeight: { type: Number },
    scrapWeight: { type: Number },
    wastageCalculated: { type: Number },
    loss: { type: Number, default: 0 },
    makingChargeEarned: { type: Number },
    ghaat: { type: Number },
    receivedAt: { type: String },
    holdingZoneId: { type: String },
  }],
  settlements: [{
    _id: { type: String },
    amount: { type: Number, default: 0 },
    type: { type: String },
    paymentMethod: { type: String },
    note: { type: String },
    createdAt: { type: String },
  }],
  metalReturns: [{
    _id: { type: String },
    returnId: { type: String },
    weight: { type: Number, default: 0 },
    purity: { type: String },
    note: { type: String },
    status: { type: String, enum: ["PENDING", "APPROVED", "REJECTED", "COMPLETED"], default: "COMPLETED" },
    createdAt: { type: Date, default: Date.now },
    requestedAt: { type: Date, default: Date.now },
    returnedAt: { type: Date },
    approvedAt: { type: Date },
    rejectedAt: { type: Date },
    rejectionReason: { type: String },
    updatedAt: { type: Date, default: Date.now },
  }],
  sessions: [{
    jti: { type: String, required: true },
    createdAt: { type: Date, default: Date.now },
    lastSeenAt: { type: Date, default: Date.now },
    expiresAt: { type: Date },
    ip: { type: String },
    device: { type: String },
  }],
  holdingZone: [{
    _id: { type: String },
    jobId: { type: String },
    orderId: { type: String },
    receivedGrossWeight: { type: Number },
    receivedNetWeight: { type: Number },
    scrapWeight: { type: Number },
    wastageCalculated: { type: Number },
    makingChargeEarned: { type: Number },
    createdAt: { type: String },
  }],
  assignedWork: String,
  workDescription: String,
  assignDate: Date,
  dueDate: Date,
  status: { type: String, enum: ["AVAILABLE", "BUSY", "ON_LEAVE", "INACTIVE", "ACTIVE", "IDLE"], default: "AVAILABLE" },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

const Karikar = (mongoose.models.Karikar || mongoose.model("Karikar", karikarSchema)) as mongoose.Model<any>;
export default Karikar;
