import 'models/product.dart';
import 'models/order.dart';
import 'models/transaction.dart';
import 'models/retailer.dart';

class MockDataService {
  static const double goldRatePerGram = 7240.0;
  static const double silverRatePerGram = 89.5;
  static const double platinumRatePerGram = 3120.0;

  static final Retailer currentRetailer = Retailer(
    id: 'RET001',
    name: 'Rahul Mehta',
    businessName: 'Mehta Jewellers',
    phone: '+91 98765 43210',
    email: 'rahul@mehtajewellers.com',
    city: 'Surat',
    state: 'Gujarat',
    gstNumber: '24ABCDE1234F1Z5',
    panNumber: 'ABCDE1234F',
    creditLimit: 1500000,
    outstandingBalance: 463200,
    memberSince: DateTime(2021, 3, 15),
    totalOrders: 142,
    totalPurchaseValue: 8750000,
    loyaltyPoints: 4375,
  );

  static final List<Map<String, dynamic>> goldRateHistory = [
    {'date': '14 Mar', 'rate': 7180.0},
    {'date': '15 Mar', 'rate': 7195.0},
    {'date': '16 Mar', 'rate': 7210.0},
    {'date': '17 Mar', 'rate': 7205.0},
    {'date': '18 Mar', 'rate': 7225.0},
    {'date': '19 Mar', 'rate': 7230.0},
    {'date': '20 Mar', 'rate': 7240.0},
  ];

  static final List<Product> products = [
    Product(
      id: 'P001',
      sku: 'GN-001',
      name: 'Classic Solitaire Ring',
      description:
          'Elegant 18K gold solitaire ring with 1.0ct round brilliant diamond. Perfect for engagement.',
      category: JewelryCategory.diamond,
      purity: MetalPurity.k18,
      grossWeight: 4.5,
      netWeight: 4.2,
      makingCharges: 15,
      imageUrls: [
        'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600',
        'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600',
        'https://images.unsplash.com/photo-1573408301185-9519f94815b3?w=600',
      ],
      stones: [
        StoneSpec(
          type: 'Diamond',
          stoneType: StoneType.natural,
          carats: 1.0,
          cut: 'Excellent',
          color: 'E',
          clarity: 'VVS1',
          pricePerCarat: 48000,
          count: 1,
        ),
      ],
      isNew: true,
      isTrending: true,
      orderCount: 287,
      rating: 4.9,
      tags: ['solitaire', 'engagement', 'diamond'],
      specs: {
        'Design Code': 'GN-001',
        'Metal': '18K Yellow Gold',
        'Total Carat Weight': '1.0 ct',
        'Diamond Cut': 'Excellent',
        'Diamond Color': 'E',
        'Diamond Clarity': 'VVS1',
        'Certificate': 'GIA',
      },
    ),
    Product(
      id: 'P002',
      sku: 'GC-002',
      name: 'Royal Kundan Choker',
      description:
          'Stunning 22K gold Kundan choker with uncut diamonds and meenakari work. Perfect for weddings.',
      category: JewelryCategory.bridal,
      purity: MetalPurity.k22,
      grossWeight: 45.2,
      netWeight: 42.0,
      makingCharges: 18,
      imageUrls: [
        'https://images.unsplash.com/photo-1619119069152-a2b331eb392a?w=600',
        'https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=600',
      ],
      isNew: false,
      isTrending: true,
      orderCount: 89,
      rating: 4.8,
      tags: ['kundan', 'bridal', 'choker', 'wedding'],
      specs: {
        'Design Code': 'GC-002',
        'Metal': '22K Yellow Gold',
        'Setting': 'Kundan',
        'Work': 'Meenakari',
        'Occasion': 'Wedding / Bridal',
      },
    ),
    Product(
      id: 'P003',
      sku: 'GD-003',
      name: 'Diamond Pave Bracelet',
      description:
          '18K white gold bracelet with 2.5ct total diamond pave setting. Timeless elegance.',
      category: JewelryCategory.diamond,
      purity: MetalPurity.k18,
      grossWeight: 8.3,
      netWeight: 7.8,
      makingCharges: 20,
      imageUrls: [
        'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600',
        'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600',
      ],
      stones: [
        StoneSpec(
          type: 'Diamond',
          stoneType: StoneType.natural,
          carats: 2.5,
          cut: 'Very Good',
          color: 'F',
          clarity: 'VS1',
          pricePerCarat: 42000,
          count: 48,
        ),
      ],
      isNew: false,
      isTrending: false,
      orderCount: 156,
      rating: 4.7,
      tags: ['pave', 'bracelet', 'diamond', 'white gold'],
      specs: {
        'Design Code': 'GD-003',
        'Metal': '18K White Gold',
        'Total Diamond Weight': '2.5 ct',
        'Diamond Cut': 'Very Good',
        'Diamond Color': 'F',
        'Diamond Clarity': 'VS1',
      },
    ),
    Product(
      id: 'P004',
      sku: 'GP-004',
      name: 'Plain Gold Bangle Set',
      description:
          'Classic 22K plain gold bangle set of 4 pieces. Timeless everyday wear.',
      category: JewelryCategory.gold,
      purity: MetalPurity.k22,
      grossWeight: 28.0,
      netWeight: 26.5,
      makingCharges: 12,
      imageUrls: [
        'https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=600',
        'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600',
      ],
      isNew: false,
      isTrending: false,
      orderCount: 412,
      rating: 4.6,
      tags: ['bangle', '22k', 'plain', 'everyday'],
      specs: {
        'Design Code': 'GP-004',
        'Metal': '22K Yellow Gold',
        'Pieces': '4 Bangles',
        'Hallmark': 'BIS Hallmarked',
        'HUID': 'HM20240104',
      },
    ),
    Product(
      id: 'P005',
      sku: 'PT-005',
      name: 'Platinum Diamond Pendant',
      description:
          'Sleek Pt950 pendant with 0.75ct solitaire. Modern minimalist design.',
      category: JewelryCategory.platinum,
      purity: MetalPurity.pt950,
      grossWeight: 3.1,
      netWeight: 2.9,
      makingCharges: 25,
      imageUrls: [
        'https://images.unsplash.com/photo-1592839997-5edf8bded432?w=600',
      ],
      stones: [
        StoneSpec(
          type: 'Diamond',
          stoneType: StoneType.natural,
          carats: 0.75,
          cut: 'Excellent',
          color: 'D',
          clarity: 'FL',
          pricePerCarat: 55000,
          count: 1,
        ),
      ],
      isNew: true,
      isTrending: false,
      orderCount: 63,
      rating: 4.8,
      tags: ['platinum', 'pendant', 'solitaire', 'minimalist'],
    ),
    Product(
      id: 'P006',
      sku: 'GE-006',
      name: 'Ruby Emerald Set',
      description:
          '18K gold necklace and earring set with natural Colombian emeralds and Burmese rubies.',
      category: JewelryCategory.gemstone,
      purity: MetalPurity.k18,
      grossWeight: 22.4,
      netWeight: 20.8,
      makingCharges: 22,
      imageUrls: [
        'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600',
        'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=600',
      ],
      stones: [
        StoneSpec(
          type: 'Emerald',
          stoneType: StoneType.natural,
          carats: 3.5,
          pricePerCarat: 35000,
          count: 5,
        ),
        StoneSpec(
          type: 'Ruby',
          stoneType: StoneType.natural,
          carats: 1.5,
          pricePerCarat: 28000,
          count: 8,
        ),
      ],
      isNew: false,
      isTrending: true,
      orderCount: 34,
      rating: 4.9,
      tags: ['gemstone', 'emerald', 'ruby', 'set'],
    ),
    Product(
      id: 'P007',
      sku: 'GN-007',
      name: 'Three-Stone Anniversary Ring',
      description:
          '18K gold three-stone ring representing past, present & future. Three brilliant-cut diamonds.',
      category: JewelryCategory.diamond,
      purity: MetalPurity.k18,
      grossWeight: 5.2,
      netWeight: 4.9,
      makingCharges: 18,
      imageUrls: [
        'https://images.unsplash.com/photo-1573408301185-9519f94815b3?w=600',
      ],
      stones: [
        StoneSpec(
          type: 'Diamond',
          stoneType: StoneType.natural,
          carats: 1.5,
          cut: 'Excellent',
          color: 'F',
          clarity: 'VS1',
          pricePerCarat: 44000,
          count: 3,
        ),
      ],
      isNew: true,
      isTrending: false,
      orderCount: 178,
      rating: 4.8,
      tags: ['three-stone', 'anniversary', 'diamond'],
    ),
    Product(
      id: 'P008',
      sku: 'GP-008',
      name: 'Gold Rope Chain',
      description:
          '22K gold rope chain necklace, 18 inch. Perfect for pendants or standalone.',
      category: JewelryCategory.gold,
      purity: MetalPurity.k22,
      grossWeight: 12.5,
      netWeight: 12.0,
      makingCharges: 10,
      imageUrls: [
        'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600',
      ],
      isNew: false,
      isTrending: false,
      orderCount: 623,
      rating: 4.5,
      tags: ['chain', 'necklace', '22k', 'everyday'],
    ),
  ];

  static final List<Order> orders = [
    Order(
      id: 'ORD001',
      orderNumber: 'LW-2024-001',
      retailerId: 'RET001',
      retailerName: 'Mehta Jewellers',
      items: [
        OrderItem(
          productId: 'P001',
          productName: 'Classic Solitaire Ring',
          sku: 'GN-001',
          imageUrl:
              'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=200',
          quantity: 2,
          unitPrice: 185420,
          purity: '18K',
        ),
      ],
      status: OrderStatus.polishing,
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      expectedDelivery: DateTime.now().add(const Duration(days: 3)),
      subtotal: 370840,
      gstAmount: 11125,
      totalAmount: 381965,
      karigarName: 'Ramesh Soni',
      karigarPhone: '+91 94562 78901',
      statusHistory: [
        OrderUpdate(
          status: OrderStatus.designApproved,
          timestamp: DateTime.now().subtract(const Duration(days: 5)),
          note: 'Design confirmed by retailer',
          updatedBy: 'Admin',
        ),
        OrderUpdate(
          status: OrderStatus.metalIssued,
          timestamp: DateTime.now().subtract(const Duration(days: 4)),
          note: '8.4g of 18K gold issued to karigar',
          updatedBy: 'Store Manager',
        ),
        OrderUpdate(
          status: OrderStatus.casting,
          timestamp: DateTime.now().subtract(const Duration(days: 3)),
          note: 'Casting complete',
          updatedBy: 'Ramesh Soni',
        ),
        OrderUpdate(
          status: OrderStatus.stoneSetting,
          timestamp: DateTime.now().subtract(const Duration(days: 2)),
          note: '1.0ct VVS1 diamond set',
          updatedBy: 'Ramesh Soni',
        ),
        OrderUpdate(
          status: OrderStatus.polishing,
          timestamp: DateTime.now().subtract(const Duration(hours: 12)),
          note: 'Final polishing in progress',
          updatedBy: 'Ramesh Soni',
        ),
      ],
    ),
    Order(
      id: 'ORD002',
      orderNumber: 'LW-2024-002',
      retailerId: 'RET001',
      retailerName: 'Mehta Jewellers',
      items: [
        OrderItem(
          productId: 'P004',
          productName: 'Plain Gold Bangle Set',
          sku: 'GP-004',
          imageUrl:
              'https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=200',
          quantity: 3,
          unitPrice: 192400,
          purity: '22K',
        ),
      ],
      status: OrderStatus.delivered,
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
      expectedDelivery: DateTime.now().subtract(const Duration(days: 7)),
      deliveredAt: DateTime.now().subtract(const Duration(days: 8)),
      subtotal: 577200,
      gstAmount: 17316,
      totalAmount: 594516,
      statusHistory: [],
    ),
    Order(
      id: 'ORD003',
      orderNumber: 'LW-2024-003',
      retailerId: 'RET001',
      retailerName: 'Mehta Jewellers',
      items: [
        OrderItem(
          productId: 'P006',
          productName: 'Ruby Emerald Set',
          sku: 'GE-006',
          imageUrl:
              'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=200',
          quantity: 1,
          unitPrice: 342000,
          purity: '18K',
        ),
      ],
      status: OrderStatus.quotationPending,
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
      subtotal: 342000,
      gstAmount: 10260,
      totalAmount: 352260,
      isCustomOrder: true,
      notes: 'Custom size required - ring size 14.',
      statusHistory: [],
    ),
  ];

  static final List<LedgerTransaction> ledgerTransactions = [
    LedgerTransaction(
      id: 'TXN001',
      referenceNumber: 'INV-2024-089',
      type: TransactionType.invoice,
      date: DateTime.now().subtract(const Duration(days: 2)),
      amount: 381965,
      balance: 463200,
      description: 'Invoice for Order LW-2024-001',
      isDebit: true,
      invoiceNumber: 'INV-2024-089',
      orderId: 'ORD001',
      isPaid: false,
      dueDate: DateTime.now().add(const Duration(days: 28)),
    ),
    LedgerTransaction(
      id: 'TXN002',
      referenceNumber: 'PAY-2024-045',
      type: TransactionType.payment,
      date: DateTime.now().subtract(const Duration(days: 8)),
      amount: 200000,
      balance: 81235,
      description: 'Payment received via NEFT',
      isDebit: false,
      isPaid: true,
    ),
    LedgerTransaction(
      id: 'TXN003',
      referenceNumber: 'INV-2024-082',
      type: TransactionType.invoice,
      date: DateTime.now().subtract(const Duration(days: 22)),
      amount: 594516,
      balance: 281235,
      description: 'Invoice for Order LW-2024-002',
      isDebit: true,
      invoiceNumber: 'INV-2024-082',
      orderId: 'ORD002',
      isPaid: false,
      dueDate: DateTime.now().add(const Duration(days: 8)),
    ),
    LedgerTransaction(
      id: 'TXN004',
      referenceNumber: 'CN-2024-012',
      type: TransactionType.creditNote,
      date: DateTime.now().subtract(const Duration(days: 35)),
      amount: 15420,
      balance: 15000,
      description: 'Credit note for quality adjustment',
      isDebit: false,
      isPaid: false,
    ),
    LedgerTransaction(
      id: 'TXN005',
      referenceNumber: 'PAY-2024-038',
      type: TransactionType.payment,
      date: DateTime.now().subtract(const Duration(days: 40)),
      amount: 350000,
      balance: 30420,
      description: 'Payment received via Cheque',
      isDebit: false,
      isPaid: true,
    ),
    LedgerTransaction(
      id: 'TXN006',
      referenceNumber: 'INV-2024-071',
      type: TransactionType.invoice,
      date: DateTime.now().subtract(const Duration(days: 65)),
      amount: 312000,
      balance: 380420,
      description: 'Invoice for custom diamond set',
      isDebit: true,
      invoiceNumber: 'INV-2024-071',
      isPaid: false,
      dueDate: DateTime.now().subtract(const Duration(days: 35)),
    ),
  ];
}
