import { Request, Response } from "express";
import mongoose from "mongoose";
import PDFDocument from "pdfkit";
import {
  SuperAdminSubscription as Subscription,
  SuperAdminUser as GlobalUser,
  SuperAdminSecurityAudit as SecurityAudit
} from "../../models/index.js";
import { isDbConnected } from "../../../lib/serverState.js";
import CustomerModel from "../../../models/Customer.js";
import InventoryModel from "../../../models/Inventory.js";
import SaleModel from "../../../models/Sale.js";

const getDbReady = () => mongoose.connection.readyState === 1 && isDbConnected();

const logExportAction = async (actor: string, format: string, details: string) => {
  try {
    if (getDbReady()) {
      await SecurityAudit.create({
        id: `AUDIT-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`,
        actor,
        action: `export-analytics-${format}`,
        entityType: "PlatformAnalytics",
        entityId: "platform-analytics",
        details,
        createdAt: new Date().toISOString(),
      });
    }
  } catch (err) {
    console.error("Failed to write platform analytics export audit log:", err);
  }
};

export const getPlatformAnalyticsReport = async (req: Request, res: Response) => {
  try {
    const actor = (req as any).user?.email || "super-admin";
    const { format = "pdf", storeId } = req.query;

    await logExportAction(actor, String(format), `Exported platform analytics report in ${format} format.`);

    if (!getDbReady()) {
      return res.status(500).json({ success: false, error: "Database offline" });
    }

    const stores = await Subscription.find({}).lean();
    const totalUsers = await GlobalUser.countDocuments({});

    // Filter store stats if specific store requested
    let filteredStores = stores;
    if (storeId) {
      filteredStores = stores.filter((s: any) => s.id === storeId);
    }

    let totalCustomers = 0;
    let totalProducts = 0;
    let totalOrders = 0;

    const storeBreakdownList: any[] = [];

    for (const s of filteredStores) {
      const tenantDb = mongoose.connection.useDb(`retailer_${s.id}`, { useCache: true });
      const CustModel = tenantDb.models.Customer || tenantDb.model("Customer", CustomerModel.schema, "customers");
      const InvModel = tenantDb.models.Inventory || tenantDb.model("Inventory", InventoryModel.schema, "inventory");
      const SaleModel = tenantDb.models.Sale || tenantDb.model("Sale", SaleModel.schema, "sales");

      const [c, p, o] = await Promise.all([
        CustModel.countDocuments({}),
        InvModel.countDocuments({}),
        SaleModel.countDocuments({})
      ]);

      totalCustomers += c;
      totalProducts += p;
      totalOrders += o;

      storeBreakdownList.push({
        id: s.id,
        shopName: s.shopName,
        status: s.status,
        planName: s.planName,
        storeType: s.storeType || "RETAILER",
        customers: c,
        products: p,
        orders: o
      });
    }

    if (format === "csv" || format === "excel") {
      let csv = "Platform Analytics Report\n";
      csv += `Generated At,${new Date().toISOString()}\n`;
      csv += `Total Stores,${stores.length}\n`;
      csv += `Total Users,${totalUsers}\n`;
      csv += `Total Customers,${totalCustomers}\n`;
      csv += `Total Products,${totalProducts}\n`;
      csv += `Total Orders,${totalOrders}\n\n`;
      
      csv += "Store ID,Shop Name,Status,Plan,Customers,Products,Orders\n";
      
      storeBreakdownList.forEach((s: any) => {
        csv += `"${s.id}","${s.shopName}","${s.status}","${s.planName}",${s.customers},${s.products},${s.orders}\n`;
      });

      res.setHeader("Content-Type", "text/csv");
      res.setHeader("Content-Disposition", "attachment; filename=platform_analytics_report.csv");
      return res.status(200).send(csv);
    }

    // PDF Format
    const doc = new PDFDocument({ margin: 40 });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", "attachment; filename=platform_analytics_report.pdf");
    doc.pipe(res);

    doc.font("Helvetica-Bold").fontSize(18).text("AURAJEWEL – PLATFORM ANALYTICS REPORT", { align: "center" });
    doc.fontSize(10).font("Helvetica").text(`Generated by: ${actor} | Date: ${new Date().toLocaleString()}`, { align: "center" });
    doc.moveDown(2);

    doc.font("Helvetica-Bold").fontSize(12).text("Platform Summary Metrics");
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(10);
    doc.text(`Total Stores Registered: ${stores.length}`);
    doc.text(`Total Global Users: ${totalUsers}`);
    doc.text(`Total Platform Customers: ${totalCustomers}`);
    doc.text(`Total Catalog Products: ${totalProducts}`);
    doc.text(`Total Orders Completed: ${totalOrders}`);
    doc.moveDown(2);

    doc.font("Helvetica-Bold").fontSize(12).text("Registered Stores Breakdown");
    doc.moveDown(0.5);

    // Table Header
    doc.font("Helvetica-Bold").fontSize(9);
    doc.text("Shop Name", 40, doc.y, { width: 140, continued: true });
    doc.text("Status", 180, doc.y, { width: 60, continued: true });
    doc.text("Plan", 240, doc.y, { width: 60, continued: true });
    doc.text("Custs", 300, doc.y, { width: 50, continued: true });
    doc.text("Prods", 350, doc.y, { width: 50, continued: true });
    doc.text("Orders", 400, doc.y, { width: 50, continued: true });
    doc.text("Type", 450, doc.y, { width: 80 });
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(9);

    storeBreakdownList.forEach((s: any) => {
      if (doc.y > 700) doc.addPage();
      doc.text(s.shopName || "N/A", 40, doc.y, { width: 140, continued: true });
      doc.text(s.status || "N/A", 180, doc.y, { width: 60, continued: true });
      doc.text(s.planName || "N/A", 240, doc.y, { width: 60, continued: true });
      doc.text(String(s.customers), 300, doc.y, { width: 50, continued: true });
      doc.text(String(s.products), 350, doc.y, { width: 50, continued: true });
      doc.text(String(s.orders), 400, doc.y, { width: 50, continued: true });
      doc.text(s.storeType || "RETAILER", 450, doc.y, { width: 80 });
      doc.moveDown(0.4);
    });

    doc.end();
  } catch (error: any) {
    return res.status(500).json({ success: false, error: error.message });
  }
};
