import { customerDb } from "../../lib/db.js";
import WishlistSchema from "../../models/Wishlist.js";
import DesignSchema from "../../models/Design.js";
import PortalCheckoutSchema from "../../models/PortalCheckout.js";
import CustomerSchema from "../../models/Customer.js";
import UserSchema from "../../models/User.js";
import InventorySchema from "../../models/Inventory.js";
import KarikarSchema from "../../models/Karikar.js";
import RateSchema from "../../models/Rate.js";
import OrderSchema from "../../models/Order.js";
import SaleSchema from "../../models/Sale.js";
import KhataSchema from "../../models/Khata.js";
import { SchemeDefinition as SchemeDefinitionSchema, SchemeEnrollment as SchemeEnrollmentSchema } from "../../models/Scheme.js";
import NotificationSchema from "../../models/Notification.js";
import NotificationPreferenceSchema from "../../models/NotificationPreference.js";
import CustomerAccountModel from "../../models/CustomerAccount.js";
import CustomerLoyaltyPointsModel from "../../models/CustomerLoyaltyPoints.js";
import LedgerHistoryModel from "../../models/LedgerHistory.js";
import InstallmentModel from "../../models/Installment.js";
import DesignMoodboardModel from "../../models/DesignMoodboard.js";
import DesignMoodboardAuditLogModel from "../../models/DesignMoodboardAuditLog.js";
import DesignApprovalModel from "../../models/DesignApproval.js";
import DesignApprovalAuditLogModel from "../../models/DesignApprovalAuditLog.js";
import MessagingConfigurationModel from "../../models/MessagingConfiguration.js";

export const Wishlist = customerDb.models.Wishlist || customerDb.model("Wishlist", WishlistSchema.schema);
export const Design = customerDb.models.Design || customerDb.model("Design", DesignSchema.schema);
export const PortalCheckout = customerDb.models.PortalCheckout || customerDb.model("PortalCheckout", PortalCheckoutSchema.schema);
export const Customer = customerDb.models.Customer || customerDb.model("Customer", CustomerSchema.schema);
export const User = customerDb.models.User || customerDb.model("User", UserSchema.schema);
export const Inventory = customerDb.models.Inventory || customerDb.model("Inventory", InventorySchema.schema);
export const Karikar = customerDb.models.Karikar || customerDb.model("Karikar", KarikarSchema.schema);
export const Rate = customerDb.models.Rate || customerDb.model("Rate", RateSchema.schema);
export const Order = customerDb.models.Order || customerDb.model("Order", OrderSchema.schema);
export const Sale = customerDb.models.Sale || customerDb.model("Sale", SaleSchema.schema);
export const Khata = customerDb.models.Khata || customerDb.model("Khata", KhataSchema.schema);
export const SchemeDefinition = customerDb.models.SchemeDefinition || customerDb.model("SchemeDefinition", SchemeDefinitionSchema.schema);
export const SchemeEnrollment = customerDb.models.SchemeEnrollment || customerDb.model("SchemeEnrollment", SchemeEnrollmentSchema.schema);
export const Notification = (customerDb.models.Notification || customerDb.model("Notification", NotificationSchema, "notifications")) as import("mongoose").Model<any>;
export const NotificationPreference = (customerDb.models.NotificationPreference || customerDb.model("NotificationPreference", NotificationPreferenceSchema, "notificationpreferences")) as import("mongoose").Model<any>;
export const MessagingConfiguration = (customerDb.models.MessagingConfiguration || customerDb.model("MessagingConfiguration", MessagingConfigurationModel.schema, "messagingconfigurations")) as import("mongoose").Model<any>;

// ─── Customer Portal Specific Collections ───────────────────────────────────
export const CustomerAccount = customerDb.models.CustomerAccount || customerDb.model("CustomerAccount", CustomerAccountModel.schema);
export const CustomerLoyaltyPoints = customerDb.models.CustomerLoyaltyPoints || customerDb.model("CustomerLoyaltyPoints", CustomerLoyaltyPointsModel.schema);
export const LedgerHistory = customerDb.models.LedgerHistory || customerDb.model("LedgerHistory", LedgerHistoryModel.schema);
export const Installment = customerDb.models.Installment || customerDb.model("Installment", InstallmentModel.schema, "installments");
export const DesignMoodboard = customerDb.models.DesignMoodboard || customerDb.model("DesignMoodboard", DesignMoodboardModel.schema, "designmoodboards");
export const DesignMoodboardAuditLog = customerDb.models.DesignMoodboardAuditLog || customerDb.model("DesignMoodboardAuditLog", DesignMoodboardAuditLogModel.schema, "designmoodboardauditlogs");
export const DesignApproval = customerDb.models.DesignApproval || customerDb.model("DesignApproval", DesignApprovalModel.schema, "designapprovals");
export const DesignApprovalAuditLog = customerDb.models.DesignApprovalAuditLog || customerDb.model("DesignApprovalAuditLog", DesignApprovalAuditLogModel.schema, "designapprovalauditlogs");
